version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: dormitory_postgres
    restart: always
    environment:
      POSTGRES_USER: dorm_user
      POSTGRES_PASSWORD: dorm_password
      POSTGRES_DB: dormitory_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
